appname: "Perl4WEB"

charset: "UTF-8"
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'

plugins:
  DBIC:
    default:
      dsn: dbi:SQLite:dbname=perl4web.db